### ISSUE TITLE
PHP error when saving an asset

### ISSUE THREAD

**Issue by brandonkelly** [gentsagency/craft-responsive-images#2]
If Responsive Images is installed, but its settings are never saved, then there will be a "Undefined offset" error that occurs whenever an asset is attempted to be saved.

This would also occur if a new volume was created, and Responsive Images' settings were not re-saved.

Error occurs due to this line:

https://github.com/gentsagency/craft-responsive-images/blob/7d076fcfd44c5ee489c44865310883f336419889/src/services/ResponsiveImagesService.php?utf8=%E2%9C%93#L34

Should probably be this instead:

```php
$volume = ResponsiveImages::$plugin->getSettings()->volumes[$image->volume->id] ?? null;
```

**Comment by pieterbeulque** [comment]
Hi Brandon,

Thanks for your bug report. I'll look into it!
